name: CI

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [nightly, stable]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose --workspace

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
    - uses: giraffate/clippy-action@main
      with:
        reporter: 'github-pr-review'
        github_token: ${{ secrets.GITHUB_TOKEN }}
